# Generated by Django 4.2.6 on 2023-10-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('carPark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='park', to='user.usermodel'),
            preserve_default=False,
        ),
    ]
