# Generated by Django 4.2.6 on 2023-10-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='countPlace',
            new_name='count_place',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='typeCar',
            new_name='type_car',
        ),
    ]
