# Generated by Django 4.2.6 on 2023-10-23 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3, 20}', 'Brand Car must be min 3 char max 30 char ')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='countPlace',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='eugenie',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='typeCar',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep')], max_length=12),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
