# Generated by Django 4.2.6 on 2023-10-26 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2,30}$', 'Name Auto Park must be only litters and min 3 char max 30 char ')])),
            ],
            options={
                'db_table': 'auto_parks',
            },
        ),
    ]
