# Generated by Django 4.2.6 on 2023-10-23 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2, 30}', 'Name Auto Park must be only litters and min 3 char max 30 char ')]),
        ),
    ]
