# Generated by Django 4.2.6 on 2023-10-23 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2, 20}', 'Name Auto Park must be only litters and min 3 char max 30 char ')]),
        ),
    ]
