# Generated by Django 4.2.6 on 2023-10-26 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilemodel_usermodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2,20}$', 'Name User must be only litters and min 3 char max 30 char ')]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='surname',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2,20}$', 'Name User must be only litters and min 3 char max 30 char ')]),
        ),
    ]
