# Generated by Django 4.2.6 on 2023-10-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carPark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('typeCar', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('countPlace', models.IntegerField()),
                ('eugenie', models.FloatField()),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='cars', to='carPark.carpark')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
